[project]
name = "music-classification-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc>=3.64.0",
    "dvclive>=3.49.0",
]
